import React from 'react'
import Image from 'next/image'

export default function page() {
  return (
    <div className='w-[80%] m-auto py-14'>

        <h1 className='text-center text-xl border-b-2 border-red-700 w-[80%] font-bold md:w-60 m-auto md:mt-16'>ABOUT THE CHAIRMAN</h1>
      <Image src='/hoblawal.jpg' height={200} width={200} className='w-[50%] md:w-[20%] m-auto rounded-2xl mt-9'/>
        <p className='py-8 leading-9'>Engr. Hamed Olugbenga Babajide LAWAL has been the Managing Director/Chief Executive Officer of Messrs. . Consteng Limited since inception in 1982 to date. H.O.B. is a 1972 graduate ofthe Elite Ahmadu Bello University Zaria, Department of Civil Engineering where he specialized in the design and construction of structural formwork systems. His working experience started with the Dutch firm, Steven Group where he had a challenging and inspiring career till he resigned in 1980 to team up with fellow Nigerian to establish Moulds (Nig.) Limited. He was the Pioneer Technical Director of Moulds Nig Limited till the inception of Consteng Limited in1982. A firm believer in the principle of Total Quality Management (TQM) and Management By Objective (MBO) and planning, Engr. Lawal is a registered Chartered Civil Engineer. Fellow Life Member of. Nigerian Society Engineers (NSE). He is also a Fellow of InstitItion of Civil Engineers of Great Britain (FICE) and the Nigerian Institution of Engineers (FNICE). 

Engr. Lawal identifies with his root, the community and the less privileged through philanthropy and membership of Ijebu Muslim College Old Students Association (IMCOSA), Egbe Bobajolu Okunrin ljebuland, Ijebu Ode Metropolitan Club and Lions Clubs International. He was a pioneer recipient of IMOSA Merit Award and served as its National President (1998— 2001). He is a past Chairman, Board of Governors of Ijebu Muslim College. HOB was the first recipient of the Fellowship Award of Metropolitan Club (FMC) and served as its Lord Mayor (1991/92). He is the Chairman of the club&apos;s business venture — Metro Arena Board of Directors. Engr Lawal is presently serving as the Babalaje of Egbe Bobajolu of Ijebuland.
Engr. Lawal served as Chairman 2000/2001 of the Civil Engineering Division of the Nigerian Society of Engineers which transformed under his leadership to the Nigerian Institution of Civil Engineers after winning many awards including the much coveted first position trophy of the NSE Group Dynamics session at the 2001 AGM. A member of the Ikorodu Doyen Lions Club since 1982 Engr Lawal has had many appointments and held many elective offices within the association, including club charter president, district governor, chairman of committees, member of Presidential Mission 30, Presidential Team 20K, Presidential Steering Committee on Africa and International director (2009 - 2011 ) as the first Nigerian, first West African and second Black African so elected to serve on the Board of the Association. He also served as the Vice Chairman of Africa CA. LCIF, CAMPAIGN 100 and the Immediate Past Africa CA Leader of Global Membership Team which led Africa to attain the status of CA8 of LCI at the 2019 Milan International Convention.
In recognition of his services to Lions clubs International, he has received 
numerous awards including Pillar of Service Award, Everyday Heroes Award, DG Excellence Award, Ambassador of Goodwill Award and thirteen International President&apos;s Appreciation Medals. A Second Century Ambassador, a Progressive Melvin Jones Fellow in the 10 Distinct Amethyst cadre and a lead donor of CAMPAIGN 100 of Lions Clubs International Foundation, Engr. Lawal is also a fellow of the Nigerian Lions Charity Foundation in the sapphire cadre. In recognition of his priceless services.11 Engr Lawal is bestowed with the trusteeship of IMCOSA, NICE, Ijebu Ode Metropolitan Club and Lions Clubs International. He was also the Chairman of Ikorodu Chamber of Commerce and Trade at one time.

Officially, Engr. H.O.B. Lawal was born on 21st February 1950. He is happily married with children and grandchildren.</p>
    </div>
  )
}
